### ISSUE TITLE
Roadmap to plugin-oidc v1.0.0

### ISSUE THREAD

**Issue by Creaous** [Nexirift/plugin-oidc#1]
See https://github.com/Nexirift/plugin-keycloak/issues/4 for more details.

- [x] Change references of `plugin-keycloak`
- [x] Reset version number back to v1.0.0
- [x] #3
- [x] Swap `Keycloak` to `OIDC`
- [x] Change plugin config to have:
  - [x] Introspect URL
  - [x] Client ID
  - [x] Client Secret

**Comment by Creaous** [comment]
Everything has been implemented, just need to publish to npm now.

**Comment by Creaous** [comment]
This project has now been released.
